# Generated by Django 4.1.7 on 2023-03-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Events',
        ),
    ]
